config/routes.rb
Rails.application.routes.draw do

  root 'login#new'
  
  get 'sign_in', to: 'login#new'
  post 'sign_in', to: 'login#create', as: 'log_in'
  post 'register', to: 'register#index'
  post 'registered', to: 'register#register'
  delete 'logout', to: 'login#destroy'
  get 'home', to: 'home#index'
  get 'doubtForm', to: 'doubt#doubtForm'
  post 'raiseDoubt', to: 'doubt#raise_doubt'
  post 'addComment', to: 'comment#add'
  get 'doubt_detail', to: 'doubt#doubt_detail'
  post 'accept_doubt', to: 'doubt#accept_doubt'
  post 'answerDoubt', to: 'doubt#answer_doubt'
  post 'escalateDoubt', to: 'doubt#escalate_doubt'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
  end

app/models/doubt.rb
class Doubt < ApplicationRecord
    enum status: [:Resolved, :Submitted, :Escalated, :Accepted]
    has_many :comments, dependent: :destroy
    has_many :TaDoubt, dependent: :destroy
    has_one :User
end

app/models/ta_doubt.rb
class TaDoubt < ApplicationRecord
    enum status: [:Resolved, :Submitted, :Escalated, :Accepted]
    has_many :Doubt
    has_many :User
end

app/models/user.rb
class User < ApplicationRecord
    enum role: [:Student, :TA, :Teacher]
    has_secure_password
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
    has_many :Doubt, dependent: :destroy
    has_many :TaDoubt
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
    end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :require_user_logged_in!
  def add
    @comment = Comment.new(comment: params[:comment], user_id: session[:user_id], doubt_id: params[:doubt_id], email: session[:email])
    if @comment.save
      redirect_to home_path
    end
  end
end

app/controllers/doubt_controller.rb
class DoubtController < ApplicationController
  before_action :require_user_logged_in!
  def doubtForm; end
  def raise_doubt
    if session[:role] == "Student"
      @doubt = Doubt.new(title: params[:title], description: params[:description], user_id: session[:user_id], status: "Submitted")
      respond_to do |format|
        if @doubt.save
          @doubt_association = TaDoubt.new(doubt_id: @doubt.id, status: "Submitted")
          if @doubt_association.save
            format.html { redirect_to home_path, notice: "Doubt raised successdfully" }
          end
        end
      end
    end
  end

  def accept_doubt
    if session[:role] == "TA"
      @doubt = Doubt.find(params[:doubt_id])
      @doubt.update(status: "Accepted", accepted_at: Time.now)
      if TaDoubt.where(doubt_id: params[:doubt_id], status: "Escalated").count > 0
        TaDoubt.where(doubt_id: params[:doubt_id], status: "Submitted").update(user_id: session[:user_id], status: "Accepted")
      else
        TaDoubt.where(doubt_id: params[:doubt_id], status: "Submitted").update(user_id: session[:user_id], status: "Accepted")
      end
      redirect_to doubt_detail_path(doubt_id: params[:doubt_id])
    end
  end

  def doubt_detail
    if session[:role] == "TA"
      @doubt = Doubt.find(params[:doubt_id])
      render "doubtDetail"
    end
  end

  def answer_doubt
    if session[:role] == "TA"
      @doubt_assoc = TaDoubt.where(user_id: session[:user_id], doubt_id: params[:doubt_id], status: "Accepted")
      @doubt_assoc.update(status: "Resolved")
      @doubt = Doubt.where(id: params[:doubt_id])
      @doubt.update(solution: params[:solution], status: "Resolved", resolved_at: Time.now)
      redirect_to home_path
    end
  end

  def escalate_doubt
    if session[:role] == "TA"
      @doubt_assoc = TaDoubt.where(doubt_id: params[:doubt_id])
      @new_row = TaDoubt.new(doubt_id: params[:doubt_id], status: "Submitted")
      TaDoubt.where(user_id:  session[:user_id], doubt_id: params[:doubt_id]).update(status: "Escalated")
      Doubt.where(id: params[:doubt_id]).update(status: "Submitted", accepted_at: Time.now)
      if @new_row.save
      redirect_to home_path
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user_logged_in!, :index

  def index
    if session[:role] == "Student"
      @doubt = Doubt.new
      @doubts = Array.new
      Doubt.all.each do |d|
        @doubt = d
        @doubt.comments = Comment.where(doubt_id: d.id)
        @doubts.push(@doubt)
      end
      render "student"
    end
    if session[:role] == "TA"
      @doubts = Doubt.all
      @doubt_assoc = TaDoubt.all
      render "TA"
    end
    if session[:role] == "Teacher"
      @no_of_doubts = Doubt.count
      @no_of_resolved_doubts = Doubt.where(status: "Resolved").count
      @no_of_doubts_escalated = Doubt.where(status: "Escalated").count
      @ta = User.where(role: "TA")
      render "Teacher"
    end
  end
  
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new; end
  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:role] = user.role
      session[:email] = user.email
      redirect_to home_path
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end
    def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: 'Logged Out'
    end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  def index
    render "index"
  end

  def register
    @user = User.new(email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation], role: params[:role])
    if @user.save
      redirect_to home_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/doubt_helper.rb
module DoubtHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/comment/index.html.erb
<h1>Comment#index</h1>
<p>Find me in app/views/comment/index.html.erb</p>

app/views/doubt/doubtDetail.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
<div class="navbar-brand col-10"><img src="https://www.codingninjas.com/assets-landing/images/CNLOGO.svg" width="7%" height="7%" class="d-inline-block align-top" alt=""></div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                     <%= link_to "Solve Doubt", home_path, class: "nav-link active" %>
                </li>
            </ul>
            <div class="d-flex">
                <%= button_to 'Logout', logout_path, method: :delete, class: "btn btn-outline-success" %>
            </div>
        </div>
    </div>
</nav>
<div class="container mt-3">
    <h2> Home </h2>
    <div class="alert-warning mt-2 mb-2"><%= notice %></div>
    <div class="alert-danger mt-2 mb-2"><%= alert %></div>
    <div class="row col-12">
        <div class="col-7">
            <div class="card mt-3">
                <div class="card-header">
                    <h5><%= @doubt.title%></h5>
                    <h6><%= @doubt.description%></h6>
                    <p class="mt-4"><small>Asked by: <%=User.find(Doubt.where(id: @doubt.id).pluck(:user_id)).pluck(:email).first%> on <%=@doubt.created_at.in_time_zone('Asia/Kolkata').strftime("%d %b, %y at %I : %M %p")%></small></p>
                </div>
                <br>
                <h6 class="col-12"><%=@doubt.comments.count%> comments</h6>
                <div class="card-body">
                    <% @doubt.comments.each do |comment| %>
                    <div class="card">
                        <div class="card-body">
                            <h6><%= comment.email%> : <%= comment.comment%></h6>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-5">
            <div class="card mt-3">
                <div class="card-body">
                    <h6>Answer</h6>
                    <%= form_with url: answerDoubt_path, :html => {:class => "form-signin"} do |f| %>
                        <%= f.text_area :solution, id: 'solution', class: 'form-control', placeholder: 'Solution' %>
                        <%= f.hidden_field :doubt_id, value: @doubt.id %>
                    <div class="row col-12">
                        <%= f.submit 'Submit', class: 'tn btn-sm btn-primary btn-block col m-2' %>
                        <% end %>
                        <% if TaDoubt.where(doubt_id: @doubt.id, status: "Escalated").count < 1 %>
                        <%= form_with url: escalateDoubt_path, :html => {:class => "form-signin col m-2"} do |f| %>
                        <%= f.hidden_field :doubt_id, value: @doubt.id %>
                        <%= f.submit 'Escalate', class: 'tn btn-sm btn-primary btn-block col-12' %>
                        <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/doubt/doubtForm.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
<div class="navbar-brand col-9"><img src="https://www.codingninjas.com/assets-landing/images/CNLOGO.svg" width="7%" height="7%" class="d-inline-block align-top" alt=""></div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <%= link_to "Home", home_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Raise Doubt", doubtForm_path, class: "nav-link active" %>
                </li>
            </ul>
            <div class="d-flex">
                <%= button_to 'Logout', logout_path, method: :delete, class: "btn btn-outline-success" %>
            </div>
        </div>
    </div>
</nav>
<div class="container mt-3">
    <h2> Raise A Doubt </h2>
    <div class="card mt-3">
        <div class="card-body">
            <%= form_with url: raiseDoubt_path, :html => {:class => "form-signin"} do |f| %>
            <%= f.text_field :title, id: 'title', class: 'form-control mb-2', placeholder: 'Title', required:''  %>
            <%= f.text_area :description, id: 'description', class: 'form-control mb-2', placeholder: 'Description', required:''  %>
            <%= f.submit 'Submit', class: 'tn btn-sm btn-primary btn-block' %>
            <% end %>
        </div>
    </div>
</div>

app/views/doubt/index.html.erb
<h1>Doubt#index</h1>
<p>Find me in app/views/doubt/index.html.erb</p>

app/views/home/TA.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
<div class="navbar-brand col-10"><img src="https://www.codingninjas.com/assets-landing/images/CNLOGO.svg" width="7%" height="7%" class="d-inline-block align-top" alt=""></div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <%= link_to "Solve Doubt", home_path, class: "nav-link" %>
                </li>
            </ul>
            <div class="d-flex">
                <%= button_to 'Logout', logout_path, method: :delete, class: "btn btn-outline-success" %>
            </div>
        </div>
    </div>
</nav>
<div class="container mt-3">
    <h2> Home </h2>
    <div class="alert-warning mt-2 mb-2"><%= notice %></div>
    <div class="alert-danger mt-2 mb-2"><%= alert %></div>
    <% @doubts.each do |doubt| %>
    <% if (doubt.status == "Submitted" || @doubt_assoc.find_by(doubt_id: doubt.id, user_id: session[:user_id], status: "Accepted")) && !@doubt_assoc.find_by(doubt_id: doubt.id, user_id: session[:user_id], status: "Escalated")%>
    <div class="card mt-3 col-7">
        <div class="card-header">
            <div class="row col-12">
                <h6 class="col"><%= doubt.title%></h6>
                <% if @doubt_assoc.find_by(doubt_id: doubt.id, user_id: session[:user_id]) && doubt.status != "Resolved"%>
                <%= link_to "View", doubt_detail_path(doubt_id: doubt.id), class: 'tn text-center btn-sm btn-primary btn-block col-1' %>
                <%end%>
                <%if doubt.status == 'Submitted'%>
                <%= form_with url: accept_doubt_path, :html => {:class => "form-signin col-1 p-0"} do |f| %>
                <%= f.submit 'Accept', class: 'tn btn-sm btn-primary btn-block' %>
                <%= f.hidden_field :doubt_id, value: doubt.id %>
                <%end%>
                <% end %>
            </div>
        </div>
    </div>
    <%end%>
    <%end%>
</div>

app/views/home/Teacher.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-brand col-11"><img src="https://www.codingninjas.com/assets-landing/images/CNLOGO.svg" width="7%" height="7%" class="d-inline-block align-top" alt=""></div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <div class="d-flex">
                <%= button_to 'Logout', logout_path, method: :delete, class: "btn btn-outline-success" %>
            </div>
        </div>
    </div>
</nav>
<div class="container mt-3">
    <h1> Dashboard </h1>
    <div class="row text-center">
        <div class="card col m-3">
            <div class="card-body">
                <h1><%= @no_of_doubts %></h1>
                <p>Total Doubts</p>
            </div>
        </div>
        <div class="card col m-3">
            <div class="card-body">
                <h1><%= @no_of_resolved_doubts %></h1>
                <p>Doubts Resolved</p>
            </div>
        </div>
        <div class="card col m-3">
            <div class="card-body">
                <h1><%= @no_of_doubts_escalated %></h1>
                <p>Doubts Escalated</p>
            </div>
        </div>
        <div class="card col m-3">
            <div class="card-body">
                <% @total = 0%>
                <% Doubt.where(status: "Resolved").each do |time| %>
                <% @total = @total + ((time.updated_at - time.accepted_at) / 1.minute).round %>
                <%end%>
                <%if Doubt.where(status: "Resolved").count > 0 %>
                <h1><%= @total/Doubt.where(status: "Resolved").count %></h1>
                <%else%>
                <h1>0</h1>
                <%end%>
                <p>Average resolution time</p>
            </div>
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-header">
            <h3 class="mb-4">TA Report</h3>
            <% @ta.each do |ta| %>
            <div class="card mb-2">
                <div class="card-body">
                    <div class="col-12"><%= ta.email %></div>
                    <div class="row col-12 mt-2">
                        <div class="col">Doubts Accepted: <%= TaDoubt.where(user_id: ta.id).count %></div>
                        <div class="col">Doubts Resolved: <%= TaDoubt.where(user_id: ta.id, status: "Resolved").count %></div>
                        <div class="col">Doubts Escalated: <%= TaDoubt.where(user_id: ta.id, status: "Escalated").count %></div>
                        <% @total = 0%>
                        <% Doubt.joins(:TaDoubt).where(TaDoubt: {user_id: ta.id, status: "Resolved"}).each do |time| %>
                        <% @total = @total + ((time.resolved_at - time.accepted_at) / 1.minute).round %>
                        <%end%>
                        <div class="col">Average resolution time:
                        <%if Doubt.joins(:TaDoubt).where(TaDoubt: {user_id: ta.id, status: "Resolved"}).count > 0%>
                            <%= @total/Doubt.joins(:TaDoubt).where(TaDoubt: {user_id: ta.id, status: "Resolved"}).count %>
                        <%else%>
                            nil
                        <%end%>
                        </div>
                    </div>
                </div>
            </div>
            <%end%>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<h1>Welcome to Home Page</h1>
<%= button_to 'Logout', logout_path, method: :delete %>

app/views/home/student.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
<div class="navbar-brand col-9"><img src="https://www.codingninjas.com/assets-landing/images/CNLOGO.svg" width="7%" height="7%" class="d-inline-block align-top" alt=""></div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <%= link_to "Home", home_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Raise Doubt", doubtForm_path, class: "nav-link" %>
                </li>
            </ul>
            <div class="d-flex">
                <%= button_to 'Logout', logout_path, method: :delete, class: "btn btn-outline-success" %>
            </div>
        </div>
    </div>
</nav>
<div class="container mt-3">
    <h2> Home </h2>
    <div class="alert-warning mt-2 mb-2"><%= notice %></div>
    <div class="alert-danger mt-2 mb-2"><%= alert %></div>
    <% @doubts.each do |doubt| %>
    <div class="card mt-3">
        <div class="card-header">
            <div class="row col-12">
                <div class="col-10">
                    <h5><%= doubt.title%></h5>
                    <h6><%= doubt.description%></h6>
                </div>
                <div class="col text-center">
                    <div class="alert-success p-1"><%=doubt.status%></div>
                </div>
            </div>
            <% if doubt.status == "Resolved" %>
            <div class="col-12 mt-3">
                <h5>Answer</h5>
                <h6><%=doubt.solution%></h6>
                <p class="font-italic">Answered by: <%=User.find(TaDoubt.where(doubt_id: doubt.id, status: "Resolved").pluck(:user_id)).pluck(:email).first%> on <%=doubt.updated_at.in_time_zone('Asia/Kolkata').strftime("%d %b, %y at %I : %M %p")%></p>
            </div>
            <%end%>
        </div>
        <div class="card-body">
            <%= form_with url: addComment_path, :html => {:class => "form-signin"} do |f| %>
            <%= f.text_area :comment, id: 'comment', class: 'form-control', placeholder: 'Comment', required: '' %>
            <%= f.hidden_field :doubt_id, value: doubt.id %>
            <%= f.submit 'Comment', class: 'tn btn-sm btn-primary btn-block mt-2' %>
            <% end %>
            <br>
            <h6 class="col-12"><%=doubt.comments.count%> comments</h6>
            <% doubt.comments.each do |comment| %>
            <div class="card mt-1">
                <div class="card-body">
                    <h6><%= comment.email%> : <%= comment.comment%></h6>
                </div>
            </div>
            <% end %>
        </div>
    </div>
    <% end %>
    <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoubtResolution</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body class="text-center" data-new-gr-c-s-check-loaded="14.989.0" data-gr-ext-installed="">
    <%= form_with url: sign_in_path, :html => {:class => "form-signin"} do |f| %>
    <form class="form-signin">
        <img class="mb-4" src="https://www.codingninjas.com/assets-landing/images/CNLOGO.svg" alt="" width="90" height="90">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <div class="alert-warning mb-2"><%= notice %></div>
        <div class="alert-danger mb-2"><%= alert %></div>
        <%= f.text_field :email, id: 'email', class: 'form-control', placeholder: 'Email address', required:'' %>
        <%= f.password_field :password, id: 'password', class: 'form-control', placeholder: 'Password', required:'' %>
        <%= f.submit 'Sign in', class: 'tn btn-lg btn-primary btn-block' %>
        <p class="mt-5 mb-3 text-muted">© Coding Ninjas</p>
    </form>
    <%end%>
    <%= yield %>
</body>
<style>
html,
body {
  height: 100%;
}

body {
  display: -ms-flexbox;
  display: -webkit-box;
  display: flex;
  -ms-flex-align: center;
  -ms-flex-pack: center;
  -webkit-box-align: center;
  align-items: center;
  -webkit-box-pack: center;
  justify-content: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

</style>
</html>

app/views/register/index.html.erb
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body class="text-center" data-new-gr-c-s-check-loaded="14.989.0" data-gr-ext-installed="">
    <%= form_with url: registered_path, :html => {:class => "form-signin"} do |f| %>
    <img class="mb-4" src="https://www.codingninjas.com/assets-landing/images/CNLOGO.svg" alt="" width="90" height="90">
    <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
    <div class="alert-warning mb-2"><%= notice %></div>
    <div class="alert-danger mb-2"><%= alert %></div>
    <%= f.text_field :email, id: 'email', class: 'form-control', placeholder: 'Email address', required:'' %>
    <%= f.password_field :password, id: 'password', class: 'form-control m-0', placeholder: 'Password', required:'' %>
    <%= f.password_field :password_confirmation, id: 'password_confirmation', class: 'form-control m-0', placeholder: 'Confirm Password', required:'' %>
    <%= f.select(:role, options_for_select(['Student', "TA", "Teacher"]), {}, {:class => 'form-select mb-2'})  %>
    <div class="col-12">
        <%= f.submit 'Sign up', class: 'col-12 btn btn-primary' %>
    </div>
    <%end%>
    <%= yield %>
</body>
<style>
    html,
    body {
        height: 100%;
    }

    body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-align: center;
        -ms-flex-pack: center;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }

    .form-signin .checkbox {
        font-weight: 400;
    }

    .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
    }

    .form-signin .form-control:focus {
        z-index: 2;
    }

    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }

    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
</style>

</html>